---
# tasks file for ../roles/webserver
- name: Activer et démarrer le service Apache
  ansible.builtin.service:
    name: apache2
    state: restarted
    enabled: yes



- name: Créer le fichier .htpasswd pour l'authentification
  community.general.htpasswd:
    path: /etc/apache2/.htpasswd
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    owner: root
    group: www-data
    mode: 0640
  with_items: "{{ common_users }}"


- name: Copier le fichier de configuration Apache personnalisé
  ansible.builtin.template:
    src: apache.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: restart apache


- name: Créer un répertoire pour la page statique
  ansible.builtin.file:
    path: /var/www/html/app
    state: directory
    mode: '0755'

- name: Copier le fichier HTML simple
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/app/index.html


